theme: jekyll-theme-minimal
title: 'Microbial Community Analysis (amplicons)'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction and Lectures
  - title: Intro to the Workshop and Core
    url: base/welcome
  - title: Schedule
    url: base/schedule
  - title: What is Bioinformatics/Genomics?
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/genomics/Genomics_a_perspective_Oct_2020.pdf
  - title: Generating Microbial Amplicons
    url: https://github.com/ucdavis-bioinformatics-training/2021-May-Microbial-Community-Analysis/blob/main/Generating_Amplicons.pdf

  - heading: Support
  - title: Zoom
    url: base/zoom
  - title: Slack
    url: base/slack
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - title: Scripts
    url: software_scripts/scripts_links

  - heading: Prerequisites
  - title: CLI
    url: base/cli_prerequisites
  - title: Introduction to R
    url: base/Intro2R/Intro2R_main
  - title: High Performance Computing
    url: base/cluster

  - heading: Data Reduction
  - title: Filetype Description
    url: data_reduction/filetypes
  - title: MCA project setup
    url: data_reduction/00-project_setup
  - title: Preprocessing Reads
    url: data_reduction/01-preproc_htstream
  - title: ASV production
    url: data_reduction/02-dada2

  - heading: Data Analysis
  - title: Prepare Analysis
    url: data_analysis/prepare_phyloseq

  - heading: ETC
  - title: Closing thoughts
    url: base/closing
  - title: Github page
    url: https://github.com/ucdavis-bioinformatics-training/2021-May-Microbial-Community-Analysis
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu
